nelmio_cors:
    defaults:
        origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['Content-Type', 'Authorization']
        allow_headers: []
        # expose_headers: ['Link']
        expose_headers: []
        max_age: 3600
    # paths:
    #     # '^/': null
    #     '^/api/':
    #         allow_origin: ['*']
    #         allow_headers: ['X-Custom-Auth']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']

